/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ex6_7_8;

import java.awt.Color;
import java.util.Timer;
import javax.swing.JButton;

/**
 *
 * @author ehsan
 */
public class Austrian_Traffic_Light extends javax.swing.JFrame {

    private final Color initColor = Color.BLACK;
    private Timer timer;
    private tLight_Task taskRed2Green;
    private tLight_Task taskGreenBlinkOn;
    private tLight_Task taskGreenBlinkOff;
    private tLight_Task taskYellow2Red;
    private tLight_Task taskRed2Red;
    private tLight_Task blinkOn;
    private tLight_Task blinkOff;
    private boolean blink;
    private final JButton[] btn;
    private final boolean[] btnInitState = new boolean[]{true, false, false};
    private final boolean[] btnStart = new boolean[]{false, true, true};
    private final boolean[] btnOpt = new boolean[]{true, true, false};

    /**
     * Creates new form French_Traffic_Light
     *
     *
     *
     *
     */
    public Austrian_Traffic_Light() {
        initComponents();
        btn = new JButton[]{startB, stopB, operB};
        blink = false;
        trafficLight1.setRedlight(initColor);
        trafficLight1.setGreenlight(initColor);
        trafficLight1.setYellowlight(initColor);
        this.setButtons(btn, btnInitState);
        timer = new Timer();

        blinkOn = new tLight_Task(initColor, Color.YELLOW, initColor, trafficLight1);
        blinkOff = new tLight_Task(initColor, initColor, initColor, trafficLight1);
        blinkOn.setNextTask(blinkOff, 500);
        blinkOff.setNextTask(blinkOn, 500);

        taskGreenBlinkOn = new tLight_Task(initColor, initColor, Color.GREEN, trafficLight1);
        taskGreenBlinkOff = new tLight_Task(initColor, initColor, initColor, trafficLight1);
        taskYellow2Red = new tLight_Task(Color.RED, initColor, initColor, trafficLight1);
        taskRed2Green = new tLight_Task(initColor, initColor, Color.GREEN, trafficLight1);
        taskRed2Red = new tLight_Task(Color.RED, Color.YELLOW, initColor, trafficLight1);

        taskGreenBlinkOn.setNextTask(taskGreenBlinkOff, 1000);
        taskGreenBlinkOff.setNextTask(taskGreenBlinkOn, 1000);
        taskYellow2Red.setNextTask(taskRed2Red, 2000);
        taskRed2Red.setNextTask(taskRed2Green, 1000);
        taskRed2Green.setNextTask(taskGreenBlinkOn, 4000);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startB = new javax.swing.JButton();
        stopB = new javax.swing.JButton();
        operB = new javax.swing.JButton();
        trafficLight1 = new Ex6_7_8.trafficLight();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        startB.setText("Start");
        startB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBActionPerformed(evt);
            }
        });

        stopB.setText("Stop");
        stopB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopBActionPerformed(evt);
            }
        });

        operB.setText("Not operational");
        operB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout trafficLight1Layout = new javax.swing.GroupLayout(trafficLight1);
        trafficLight1.setLayout(trafficLight1Layout);
        trafficLight1Layout.setHorizontalGroup(
            trafficLight1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
        );
        trafficLight1Layout.setVerticalGroup(
            trafficLight1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(trafficLight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(operB)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stopB)
                            .addComponent(startB))
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(startB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stopB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(operB)
                .addContainerGap(371, Short.MAX_VALUE))
            .addComponent(trafficLight1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBActionPerformed
        // TODO add your handling code here:
        if (blink) {
            stopB.doClick();
        }

        this.setButtons(btn, btnStart);
        trafficLight1.setRedlight(Color.RED);
        trafficLight1.setGreenlight(initColor);
        trafficLight1.setYellowlight(initColor);
        trafficLight1.repaint();
        timer = new Timer();

        taskGreenBlinkOn = new tLight_Task(initColor, initColor, Color.GREEN, trafficLight1);
        taskGreenBlinkOff = new tLight_Task(initColor, initColor, initColor, trafficLight1);
        taskYellow2Red = new tLight_Task(Color.RED, initColor, initColor, trafficLight1);
        taskRed2Green = new tLight_Task(initColor, initColor, Color.GREEN, trafficLight1);
        taskRed2Red = new tLight_Task(Color.RED, Color.YELLOW, initColor, trafficLight1);

        taskGreenBlinkOn.setNextTask(taskGreenBlinkOff, 1000);
        taskGreenBlinkOff.setNextTask(taskGreenBlinkOn, 1000);
        taskYellow2Red.setNextTask(taskRed2Red, 2000);
        taskRed2Red.setNextTask(taskRed2Green, 1000);
        taskRed2Green.setNextTask(taskGreenBlinkOn, 4000);

        timer.schedule(taskRed2Red, 3000);


    }//GEN-LAST:event_startBActionPerformed

    private void stopBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopBActionPerformed
        // TODO add your handling code here:
        this.setButtons(btn, btnInitState);
        blink = false;
        trafficLight1.setRedlight(initColor);
        trafficLight1.setGreenlight(initColor);
        trafficLight1.setYellowlight(initColor);
        taskRed2Green.cancelNextTask();
        taskGreenBlinkOn.cancelNextTask();
        taskGreenBlinkOff.cancelNextTask();
        taskYellow2Red.cancelNextTask();
        taskRed2Red.cancelNextTask();
        blinkOff.cancelNextTask();
        blinkOn.cancelNextTask();
        timer.cancel();
        trafficLight1.repaint();


    }//GEN-LAST:event_stopBActionPerformed

    private void operBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operBActionPerformed
        // TODO add your handling code here:
        stopB.doClick();
        blink = true;
        this.setButtons(btn, btnOpt);
        timer = new Timer();
        blinkOn = new tLight_Task(initColor, Color.YELLOW, initColor, trafficLight1);
        blinkOff = new tLight_Task(initColor, initColor, initColor, trafficLight1);
        blinkOn.setNextTask(blinkOff, 500);
        blinkOff.setNextTask(blinkOn, 500);

        timer.schedule(blinkOn, 500);

    }//GEN-LAST:event_operBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Austrian_Traffic_Light.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Austrian_Traffic_Light.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Austrian_Traffic_Light.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Austrian_Traffic_Light.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Austrian_Traffic_Light().setVisible(true);
            }
        });
    }

    public void setButtons(JButton[] btn, boolean[] btnState) {
        for (int i = 0; i < btn.length; i++) {
            btn[i].setEnabled(btnState[i]);
            btn[i].setFocusable(btnState[i]);

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton operB;
    private javax.swing.JButton startB;
    private javax.swing.JButton stopB;
    private Ex6_7_8.trafficLight trafficLight1;
    // End of variables declaration//GEN-END:variables

}
